### ISSUE TITLE
cross build on Ubuntu 20.04.2 LTS on WSL2 fails on luasocket

### ISSUE THREAD

**Issue by ghost** [pocomane/lua_static_battery#1]
Cross building on Ubuntu 20.04.2 LTS on WSL2 and on a native Ubuntu 21.04 using

```
wget https://raw.githubusercontent.com/pocomane/lua_static_battery/master/pack.sh
chmod +x pack.sh
TARGET=windows ./pack.sh update
chmod +x build/pack/build.sh
TARGET=windows build/pack/build.sh
```
failed with this output:

[pack.output.txt](https://github.com/pocomane/lua_static_battery/files/6696334/pack.output.txt)
[build.output.txt](https://github.com/pocomane/lua_static_battery/files/6696333/build.output.txt)

**Comment by pocomane** [comment]
It seems that the newer musl.cc toolchains already have a wrapper for the inet_pton function, so luasocket does not need to be compiled with -DLUASOCKET_INTED_PTON. I fixed this on the last commit.

Thanks for the report!

**Comment by ghost** [comment]
After a quick test on another Ubuntu on WSL2 the luasocket build seems fixed, thank you! I'll test later on the same machine. Unfortunately the build fails again by not finding the lua library. Maybe it's a WSL issue, I'll also investigate this further. But for now the output is [build.output.txt](https://github.com/pocomane/lua_static_battery/files/6700459/build.output.txt)

**Comment by pocomane** [comment]
That error is expected: it is due to the luasocket makefile trying to compile a dynamic version of the library. In fact that error is ignored by build.sh and the script does not halt. The rest of the output seems good: you should have lua.exe, merge_lua.exe etc in the build/ subfolder.

The only issue is at end of the output: it was unable to generate the .zip archive since the zip command is not installed. I forgot to mention this dependency in the Readme, since it is needed for windows crossbuild only. I will add it.

**Comment by ghost** [comment]
You're right, works as expected. Thanks for the fix!
